version: '3'
services:
  config-server:
    build:
      context: .
    ports:
      - "8888:8888"
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/volha-dzehtsiarenka/config_spring_cloud
