server:
  port: 8888
spring:
  application:
    name: carservice-spring-cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/volha-dzehtsiarenka/config_spring_cloud.git
          username: volha-dzehtsiarenka
          password: ******
          searchPaths: {carservice}
